version: '3'
services:
  web1:
    image: nginx
    volumes:
      - ./index1.html:/usr/share/nginx/html/index.html

  web2:
    image: nginx
    volumes:
      - ./index2.html:/usr/share/nginx/html/index.html

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - web1
      - web2

  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8081:80"
    depends_on:
      - web1
      - web2
